"""

You are given two strings, str_1 and str_2, where str_2 is generated by 

randomly shuffling str_1 and then adding one letter at a random position.

Write a function that returns the letter that was added to str_2.

"""

def csFindAddedLetter(str_1, str_2):
    str_2_list = list(str_2)
    for letter in str_1:
        if letter in str_2_list:
            str_2_list.remove(letter)
    
    return str_2_list[0]